# Generated by Django 5.2.6 on 2025-09-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField()),
                ('release_date', models.ImageField(upload_to='')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
