# Generated by Django 5.2.6 on 2025-10-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='movies/images'),
        ),
    ]
