# Generated by Django 5.2.6 on 2025-10-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='movies/images/default.jpg', null=True, upload_to='movies/images'),
        ),
    ]
