# Generated by Django 5.2.6 on 2025-10-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='movie/images/default.jpg', null=True, upload_to='movie/images/'),
        ),
    ]
